In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import roc_curve
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('wine.csv')
data=pd.DataFrame(data=data)
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [3]:
y = data.quality
x = data.drop('quality', axis=1)

In [4]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
data.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6

In [6]:
data.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [7]:
data.shape

(1599, 12)

In [8]:
x.shape

(1599, 11)

In [9]:
y.shape

(1599,)

In [10]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.34,random_state=0)

In [11]:
train_x.shape

(1055, 11)

In [12]:
test_x.shape

(544, 11)

In [13]:
train_y.shape

(1055,)

In [14]:
test_y.shape

(544,)

In [15]:
lg=LogisticRegression()

In [16]:
lg.fit(train_x,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
pred=lg.predict(test_x)
print(pred)

[6 5 6 5 6 5 5 6 5 5 5 5 6 5 6 6 7 6 6 5 6 5 6 5 5 5 5 6 5 6 6 6 6 5 6 6 5
 5 6 6 5 6 7 6 6 5 6 6 5 6 5 5 6 6 5 5 5 5 6 5 5 6 6 6 5 6 5 6 6 6 5 6 5 5
 5 6 5 5 5 6 5 5 6 6 6 5 6 5 5 5 5 5 6 5 6 5 6 5 5 6 7 6 6 6 5 5 5 5 6 5 6
 5 6 5 6 6 6 7 6 6 5 6 6 5 6 6 5 5 6 6 5 5 6 6 6 5 6 5 6 5 6 5 6 5 6 6 6 6
 6 5 6 6 5 6 6 6 5 5 6 6 6 6 6 5 6 5 6 6 5 6 6 5 5 7 6 7 7 7 6 5 5 7 5 6 7
 5 6 6 5 6 6 6 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 6 6 5 6 5 6 7 5 5 6 6 6 5 5 6
 6 6 5 6 6 6 5 5 5 6 5 6 6 6 6 6 7 6 5 5 5 5 6 5 5 5 5 6 5 5 5 5 6 5 5 5 5
 5 5 7 5 6 5 5 5 5 6 6 5 6 6 6 6 6 6 5 7 6 5 7 6 6 6 5 5 5 6 6 6 6 6 5 5 6
 5 5 5 5 6 5 5 5 6 6 5 5 5 5 5 6 5 5 5 7 6 6 5 7 5 5 6 6 6 5 7 5 5 5 7 5 5
 6 5 6 6 6 5 5 5 5 5 6 6 5 5 5 6 6 6 6 5 6 7 5 6 6 6 6 5 6 5 6 5 5 5 6 5 5
 5 5 5 6 5 5 6 6 6 6 6 6 5 5 5 6 6 5 6 5 6 5 5 7 5 6 5 5 6 5 5 5 5 5 5 5 6
 6 5 6 5 5 5 6 6 5 6 5 5 6 6 6 7 6 5 6 6 6 5 5 5 6 5 6 6 7 6 6 5 5 6 5 6 5
 6 5 6 7 5 5 6 5 6 7 6 5 5 5 6 5 5 7 5 5 5 5 6 5 5 5 6 5 5 5 6 5 5 5 6 5 6
 7 5 6 5 7 5 5 6 5 5 6 5 

In [18]:
print("accuracy score:",accuracy_score(pred,test_y))

accuracy score: 0.6231617647058824


In [19]:
print(confusion_matrix(test_y,pred))

[[  0   0   4   0   0   0]
 [  0   0  13   4   0   0]
 [  0   0 183  53   1   0]
 [  0   0  72 145  14   0]
 [  0   0   4  35  11   0]
 [  0   0   0   3   2   0]]


In [20]:
print(classification_report(test_y,pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        17
           5       0.66      0.77      0.71       237
           6       0.60      0.63      0.62       231
           7       0.39      0.22      0.28        50
           8       0.00      0.00      0.00         5

    accuracy                           0.62       544
   macro avg       0.28      0.27      0.27       544
weighted avg       0.58      0.62      0.60       544



In [21]:
mnb=MultinomialNB()
mnb.fit(train_x,train_y)
predmnb=mnb.predict(test_x)
print(accuracy_score(test_y,predmnb))
print(confusion_matrix(test_y,predmnb))
print(classification_report(test_y,predmnb))

0.41544117647058826
[[  0   0   1   1   2   0]
 [  5   0   4   3   5   0]
 [  5   0 111  67  54   0]
 [ 15   0  61  97  58   0]
 [  9   0   5  18  18   0]
 [  1   0   1   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        17
           5       0.61      0.47      0.53       237
           6       0.52      0.42      0.46       231
           7       0.13      0.36      0.19        50
           8       0.00      0.00      0.00         5

    accuracy                           0.42       544
   macro avg       0.21      0.21      0.20       544
weighted avg       0.50      0.42      0.44       544



In [22]:
svc=SVC(kernel='rbf')
svc.fit(train_x,train_y)
svc.score(train_x,train_y)
predsvc=svc.predict(test_x)
print(accuracy_score(test_y,predmnb))
print(confusion_matrix(test_y,predmnb))
print(classification_report(test_y,predmnb))

0.41544117647058826
[[  0   0   1   1   2   0]
 [  5   0   4   3   5   0]
 [  5   0 111  67  54   0]
 [ 15   0  61  97  58   0]
 [  9   0   5  18  18   0]
 [  1   0   1   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        17
           5       0.61      0.47      0.53       237
           6       0.52      0.42      0.46       231
           7       0.13      0.36      0.19        50
           8       0.00      0.00      0.00         5

    accuracy                           0.42       544
   macro avg       0.21      0.21      0.20       544
weighted avg       0.50      0.42      0.44       544



In [23]:
dtc=DecisionTreeClassifier()
dtc.fit(train_x,train_y)
dtc.score(train_x,train_y)
preddtc=dtc.predict(test_x)
print(accuracy_score(test_y,preddtc))
print(confusion_matrix(test_y,preddtc))
print(classification_report(test_y,preddtc))

0.5882352941176471
[[  0   0   3   1   0   0]
 [  0   1   9   5   2   0]
 [  0   8 154  66   9   0]
 [  1  12  50 136  28   4]
 [  0   0   5  14  29   2]
 [  0   0   2   1   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.05      0.06      0.05        17
           5       0.69      0.65      0.67       237
           6       0.61      0.59      0.60       231
           7       0.41      0.58      0.48        50
           8       0.00      0.00      0.00         5

    accuracy                           0.59       544
   macro avg       0.29      0.31      0.30       544
weighted avg       0.60      0.59      0.59       544



In [24]:
dtc=KNeighborsClassifier()
dtc.fit(train_x,train_y)
dtc.score(train_x,train_y)
preddtc=dtc.predict(test_x)
print(accuracy_score(test_y,preddtc))
print(confusion_matrix(test_y,preddtc))
print(classification_report(test_y,preddtc))

0.47794117647058826
[[  0   0   2   1   1   0]
 [  0   0  14   3   0   0]
 [  0   0 150  85   2   0]
 [  0   1 113  97  20   0]
 [  0   0  11  25  13   1]
 [  0   0   0   2   3   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        17
           5       0.52      0.63      0.57       237
           6       0.46      0.42      0.44       231
           7       0.33      0.26      0.29        50
           8       0.00      0.00      0.00         5

    accuracy                           0.48       544
   macro avg       0.22      0.22      0.22       544
weighted avg       0.45      0.48      0.46       544



In [25]:
y_pred_prob=lg.predict_proba(test_x)[:,1]
y_pred_prob

array([0.01191832, 0.10515174, 0.0092445 , 0.04400476, 0.01904332,
       0.02493559, 0.05467941, 0.01452899, 0.09263294, 0.03758379,
       0.04404412, 0.04123192, 0.03882352, 0.05625725, 0.06640183,
       0.01183763, 0.00826607, 0.02592368, 0.04059595, 0.07344848,
       0.03255995, 0.04035384, 0.0362741 , 0.01988142, 0.03093731,
       0.01227371, 0.01238188, 0.01251937, 0.00890531, 0.02336414,
       0.01316727, 0.01835131, 0.04009721, 0.05150063, 0.05808602,
       0.01327953, 0.04261013, 0.05828635, 0.02141721, 0.04402871,
       0.02629992, 0.047619  , 0.00927549, 0.00734595, 0.02697552,
       0.04898597, 0.05682527, 0.01101271, 0.03643181, 0.01028854,
       0.05881669, 0.03412245, 0.06820282, 0.00646645, 0.016417  ,
       0.01707836, 0.00817585, 0.03807654, 0.00890445, 0.0450709 ,
       0.06193404, 0.02914417, 0.02425948, 0.01662265, 0.05270048,
       0.03299463, 0.07191883, 0.01493909, 0.01570524, 0.02339185,
       0.0296256 , 0.01892428, 0.07099512, 0.02548607, 0.02904

In [27]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr.fit(train_x,train_y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [28]:
rfr.score(train_x,train_y)

0.9032098637183689

In [29]:
rfr=RandomForestRegressor(n_estimators=100,random_state=46)
rfr.fit(train_x,train_y)
rfr.score(train_x,train_y)

0.9302754489246322

In [30]:
rfr=RandomForestRegressor(n_estimators=400,random_state=56)
rfr.fit(train_x,train_y)
rfr.score(train_x,train_y)

0.9331445231753727

In [31]:
from sklearn.ensemble import GradientBoostingRegressor
gbr=GradientBoostingRegressor()
gbr.fit(train_x,train_y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [36]:
gbr=GradientBoostingRegressor(n_estimators=500,random_state=76)
gbr.fit(train_x,train_y)
gbr.score(train_x,train_y)

0.9165979922500564

In [37]:
mnb=MultinomialNB()
score=cross_val_score(mnb,x,y,cv=5)
print("Score:",score)
print("Mean scores",score.mean())
print("Std Deviation",score.std())
y_pred=cross_val_predict(mnb,x,y,cv=5)
print('Y prediction values')
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
conf_mat
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

Score: [0.50621118 0.43302181 0.42367601 0.3427673  0.43217666]
Mean scores 0.42757059023755384
Std Deviation 0.051849861140390245
Y prediction values
[6 5 5 ... 6 6 6]


0.4277673545966229

In [38]:
dtc=DecisionTreeClassifier()
score=cross_val_score(dtc,x,y,cv=8,scoring='f1_macro')
print('F1-score:',score)
print('Mean Scores',score.mean())
print('standard deviation',score.std())
y_pred=cross_val_predict(mnb,x,y,cv=8)
print('Y prediction values')
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
conf_mat

F1-score: [0.22214398 0.26767079 0.25851737 0.27751289 0.21414751 0.24375543
 0.26105485 0.30689489]
Mean Scores 0.2564622142583971
standard deviation 0.027989443488667984
Y prediction values
[6 5 5 ... 6 6 6]


array([[  2,   0,   2,   2,   4,   0],
       [  2,   0,  13,  21,  17,   0],
       [ 15,   0, 333, 213, 120,   0],
       [ 30,   0, 177, 272, 159,   0],
       [ 21,   0,  24,  69,  85,   0],
       [  1,   0,   3,   5,   9,   0]], dtype=int64)

In [39]:
knn=KNeighborsClassifier()
score=cross_val_score(knn,x,y,cv=8,scoring='accuracy')
print("Accuracy Score:",score)
print("Mean scores",score.mean())
print("Std Deviation",score.std())
y_pred=cross_val_predict(knn,x,y,cv=10)
print('Y prediction values')
print(y_pred)
print("y_pred.shape",y_pred.shape)
conf_mat=confusion_matrix(y,y_pred)
conf_mat

Accuracy Score: [0.408867   0.4950495  0.485      0.47       0.41       0.40201005
 0.40909091 0.42639594]
Mean scores 0.4383016748066058
Std Deviation 0.03603005026954211
Y prediction values
[5 6 5 ... 6 6 6]
y_pred.shape (1599,)


array([[  0,   0,   5,   3,   2,   0],
       [  0,   1,  33,  17,   2,   0],
       [  0,   6, 397, 265,  13,   0],
       [  0,   6, 309, 274,  49,   0],
       [  0,   4,  45, 106,  42,   2],
       [  0,   0,   4,  10,   4,   0]], dtype=int64)

In [40]:
sv=SVC()
score=cross_val_score(sv,x,y,cv=8,scoring='accuracy')
print("Accuracy Score:",score)
print("Mean scores",score.mean())
print("Std Deviation",score.std())
y_pred=cross_val_predict(knn,x,y,cv=10)
print('Y prediction values')
print(y_pred)
print("y_pred.shape",y_pred.shape)
conf_mat=confusion_matrix(y,y_pred)
conf_mat
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

Accuracy Score: [0.47783251 0.55445545 0.515      0.53       0.485      0.48743719
 0.48484848 0.48730964]
Mean scores 0.5027354091635011
Std Deviation 0.02572783313001607
Y prediction values
[5 6 5 ... 6 6 6]
y_pred.shape (1599,)


0.44652908067542213

In [41]:
def svmkernel(ker):
    svc=SVC(kernel=ker)
    score=cross_val_score(sv,x,y,cv=8,scoring='accuracy')
    print("Accuracy Score:",score)
    print("Mean scores",score.mean())
    print("Std Deviation",score.std())
    y_pred=cross_val_predict(svc,x,y,cv=10)
    
    conf_mat=confusion_matrix(y,y_pred)
    print(conf_mat)

In [42]:
svmkernel('rbf')

Accuracy Score: [0.47783251 0.55445545 0.515      0.53       0.485      0.48743719
 0.48484848 0.48730964]
Mean scores 0.5027354091635011
Std Deviation 0.02572783313001607
[[  0   0   8   2   0   0]
 [  0   0  29  22   2   0]
 [  0   2 441 233   5   0]
 [  0   0 285 321  32   0]
 [  0   0  38 122  39   0]
 [  0   0   4  12   2   0]]


In [ ]:
svmkernel('poly')

Accuracy Score: [0.47783251 0.55445545 0.515      0.53       0.485      0.48743719
 0.48484848 0.48730964]
Mean scores 0.5027354091635011
Std Deviation 0.02572783313001607


In [ ]:
svrbf=SVC(kernel='rbf')
score=cross_val_score(svrbf,x,y,cv=8)
print("Mean scores",score.mean())
print("Std Deviation",score.std())
y_pred=cross_val_predict(svrbf,x,y,cv=10)
print('Y prediction values')
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
print(conf_mat)